[Config]
model="resnet50_cifar100"
dataset="cifar100"
name="resnet50_pruning_finished_obd_0.5"
mask="Outputs/pruning_resnent50_cifar100/Pruning_1/obd/0.5/mask.pkl"

[Indicator]
    [Indicator.builtin]
    input="test_dataloader"
    model="model"