[Config]
model="resnet50_cifar100"
dataset="cifar100"
name="resnet50_pruning_finished_obd04"
mask="Outputs/pruning_resnent50_cifar100/Pruning_1/obd/0.4/mask.pkl"

[Explanation_1]

    [Explanation_1.deeplift]
    input="test_dataloader"
    save="True"
    evaluate="True"
    all_load="True"