[Config]
model="vgg16_cifar100"
dataset="cifar100"
name="vgg16_pruning_finished_obd_0.4"
mask="Outputs/pruning_vgg16_cifar100/Pruning_1/obd/0.4/mask.pkl"

[Indicator]
    [Indicator.builtin]
    input="test_dataloader"
    model="model"