[Config]
model="vgg16_cifar100"
dataset="cifar100"
name="vgg16_pruning_finished_obd04"
mask="Outputs/pruning_vgg16_cifar100/Pruning_1/obd/0.4/mask.pkl"

[Adversarial_1]
    [Adversarial_1.fgsm]
    input="test_dataloader"
    save="True"
    other_models="densenet121_cifar100, resnet50_cifar100, googlenet_cifar100, mobilenetv2_cifar100, inceptionv3_cifar100"

    [Adversarial_1.bim]
    input="test_dataloader"
    save="True"
    other_models="densenet121_cifar100, resnet50_cifar100, googlenet_cifar100, mobilenetv2_cifar100, inceptionv3_cifar100"

    [Adversarial_1.difgsm]
    input="test_dataloader"
    save="True"
    other_models="densenet121_cifar100, resnet50_cifar100, googlenet_cifar100, mobilenetv2_cifar100, inceptionv3_cifar100"

    [Adversarial_1.tifgsm]
    input="test_dataloader"
    save="True"
    other_models="densenet121_cifar100, resnet50_cifar100, googlenet_cifar100, mobilenetv2_cifar100, inceptionv3_cifar100"

    [Adversarial_1.mifgsm]
    input="test_dataloader"
    save="True"
    other_models="densenet121_cifar100, resnet50_cifar100, googlenet_cifar100, mobilenetv2_cifar100, inceptionv3_cifar100"

    [Adversarial_1.sinifgsm]
    input="test_dataloader"
    save="True"
    other_models="densenet121_cifar100, resnet50_cifar100, googlenet_cifar100, mobilenetv2_cifar100, inceptionv3_cifar100"

    [Adversarial_1.pgd]
    input="test_dataloader"
    save="True"
    other_models="densenet121_cifar100, resnet50_cifar100, googlenet_cifar100, mobilenetv2_cifar100, inceptionv3_cifar100"

    [Adversarial_1.ssa]
    input="test_dataloader"
    save="True"
    other_models="densenet121_cifar100, resnet50_cifar100, googlenet_cifar100, mobilenetv2_cifar100, inceptionv3_cifar100"

    [Adversarial_1.advgan]
    input="test_dataloader"
    save="True"
    other_models="densenet121_cifar100, resnet50_cifar100, googlenet_cifar100, mobilenetv2_cifar100, inceptionv3_cifar100"

    [Adversarial_1.cw]
    input="test_dataloader"
    save="True"
    other_models="densenet121_cifar100, resnet50_cifar100, googlenet_cifar100, mobilenetv2_cifar100, inceptionv3_cifar100"