[Config]
model="vgg16_cifar100"
dataset="cifar100"
name="vgg16_pruning_finished_obd04"
mask="Outputs/pruning_vgg16_cifar100/Pruning_1/obd/0.4/mask.pkl"

[Explanation_1]

    [Explanation_1.sm]
    input="test_dataloader"
    save="True"
    evaluate="True"
    all_load="True"