[Config]
model="vgg16_cifar100"
dataset="cifar100"
name="vgg16_pruning_finished_asl_0.45"
mask="Outputs/pruning_vgg16_cifar100/Pruning_1/asl/0.45/mask.pkl"

[Indicator]
    [Indicator.builtin]
    input="test_dataloader"
    model="model"