[Config]
model="resnet50_cifar100"
dataset="cifar100"
name="resnet50_pruning_finished_taylor_0.45"
mask="Outputs/pruning_resnent50_cifar100/Pruning_1/taylor/0.45/mask.pkl"

[Indicator]
    [Indicator.builtin]
    input="test_dataloader"
    model="model"