[advgan]
image_nc=3
box_min=0
box_max=1
eps="16/255"
epochs=50
model_num_labels=1000

[fgsm]
eps="8/255"

[bim]
eps="8/255"
alpha="2/255"
steps=10

[pgd]
eps="8/255"
alpha="2/255"
steps=10
random_start="True"

[difgsm]
eps="8/255"
alpha="2/255"
steps=10
decay=0.9
resize_rate=0.9
diversity_prob=0.5
random_start="False"

[tifgsm]
eps="8/255"
alpha="2/255"
steps=10
decay=0.0
kernel_name="gaussian"
len_kernel=15
nsig=3
resize_rate=0.9
diversity_prob=0.5
random_start="False"

[mifgsm]
eps="8/255"
alpha="2/255"
steps=10
decay=1.0

[sinifgsm]
eps="8/255"
alpha="2/255"
steps=10
decay=1.0
m=5

[cw]
c=1
kappa=0
steps=50
lr=0.01

[ssa]
min=0
max=1
num_iter=10
eps="16/255"
momentum=1.0
N=20
rho=0.5
sigma="16/255"
