[guided_ig]
steps=15

[agi]
epsilon=0.05
max_iter=20
topk=20

[big]
data_min=0
data_max=1
epsilons="[36, 64, 0.3 * 255, 0.5 * 255, 0.7 * 255, 0.9 * 255, 1.1 * 255]"
gradient_steps=50

[ig]
gradient_steps=50

[sg]
stdevs=0.15
gradient_steps=50