[Config]
model="resnet50_cifar100"
dataset="cifar100"

# [Mutants]
#     [Mutants.datamissing]
#     input="test_dataloader"
#     output="missed_test_dataloader"

# [Adversarial]
#     [Adversarial.fgsm]
#     input="missed_test_dataloader"
#     save="True"

#     [Adversarial.bim]
#     input="test_dataloader"
#     save="True"

# [Explanation]
#     [Explanation.fast_ig]
#     input="test_dataloader"
#     save="True"
#     evaluate="True"

#     [Explanation.saliencymap]
#     input="test_dataloader"
#     save="True"
#     evaluate="True"

[Pruning]
    [Pruning.asl]
    input="train_dataloader"
    output="asl_pruned_model_0_65"

[Indicator]
    [Indicator.builtin]
    input="test_dataloader"
    model="asl_pruned_model_0_65"