[asl]
lv=10.0
epochs=1000
lr=0.1
sparsity='adaptive'
pthres=1000
pruning_ratio=0.65


[greg]
img_size=224
num_classes=1000
num_chennels=3
momentum=0.9
weight_decay=1e-4
reg_granularity_recover=1e-4
reg_granularity_prune=1e-4
reg_granularity_pick=1e-5
reg_upper_limit_pick=1e-2
reg_upper_limit=1.0
lr_prune=0.001
test_interval=2000
update_reg_interval=5
stabilize_reg_interval=40000
n_conv_within_block=3
res="True"
stage_pr="[0,0.675,0.675,0.675,0.675,0.675]"
skip_layers=""
pick_pruned="min"

[obd]
alpha=0.000001
pruning_ratio=0.65

[taylor]
alpha=0.000001
pruning_ratio=0.65